services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
    networks:
      - laravel_network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY_HERE
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: root
      MYSQL_PASSWORD: helloworld
      MYSQL_ROOT_PASSWORD: helloworld
    networks:
      - laravel_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    networks:
      - laravel_network

volumes:
  dbdata:


networks:
  laravel_network:
